config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lists
  #get '/lists/:id', to: 'list#show', as: 'list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_members
end

app/models/list_member.rb
class ListMember < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many(:tweets,
             join_table: "replies",
             foreign_key: "tweet_or_id",
             association_foreign_key: "tweet_rp_id")
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :user_profile
  has_many :tweets
  has_many :lists

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]
  before_action :authenticate_user!, only: [:index]

  def index
    @lists = List.where(user: current_user)
  end

  #/list/:id
  def show
    list_members = ListMember.where(list: @list)

    tweets = []
    list_members.each do |lm|
      lm.user.tweets.each do |t|
        tweets.push(t)
      end
    end

    @tweets = tweets.sort_by(&:created_at).reverse
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'Author was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  private

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name, :desc, :user_id)
    end
end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twttr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.haml
= form_for(list) do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :desc
    = f.text_field :desc
  .field
    = f.label :user_id
    = f.number_field :user_id
  .actions
    = f.submit

app/views/lists/new.html.haml
%h1 New List
= render 'form', list: @list
= link_to 'Back', lists_path

app/views/lists/show.html.haml
-@tweets.each do |t|
  %h3=t.content
  //Añade respuestas para cada tweet
  -t.tweets.reverse.each do |r|
    %h5=r.content